### ISSUE TITLE
mod_jea_slider-1.2.zip

### ISSUE THREAD

**Issue by rnervi** [JoomlaEstateAgency/mod_jea_slider#1]
it does not install on a new clean j4.3.4
"Internal Server Error"
ty

**Comment by ilhooq** [comment]
mod_jea_slider-1.2 is an old release. There is not yet an official release for Joomla 4 but you can try to install the [development version](https://github.com/JoomlaEstateAgency/mod_jea_slider/archive/refs/heads/master.zip)

**Comment by rnervi** [comment]
ty

**Comment by rnervi** [comment]
sorry bother you but...

as the export(3.10) is not working (it only works for tables not for images)

I am trying to make an export - import of property tables.

In the J4 version these fields are not in the table:

`owner_name`, `dpe_energy`, `dpe_ges`,

 

so I manually added them to db structure to import records
